[package]
name = "bloog"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7.9", features = ["multipart", "macros", "form"] }
base64 = "0.22.1"
chrono = { version = "0.4.38" , features = ["serde", "rkyv-64", "alloc"]}
clap = { version = "4.5.21", features = ["env"] }
futures = "0.3.31"
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png", "webp"] }
itertools = "0.13.0"
maud = { version = "0.26.0", features = ["axum"] }
object_store = "0.11.1"
regex = "1.11.1"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
url = "2.5.4"
serde = { version = "1.0.215", features = ["derive"] }
rkyv = { version = "0.8.9", features = ["std", "alloc"] }
anyhow = "1.0.93"
thiserror = "2.0.3"
postcard = { version = "1.1.1", features = ["use-std"]}
validator = { version = "0.19.0" , features = ["derive", "unic"]}
lazy_static = "1.5.0"
serde_urlencoded = "0.7.1"
bytes = "1.9.0"
