[package]
name = "bloog"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.1", features = ["multipart", "macros", "form"] }
base64 = { version = "0.22.1" }
chrono = { version = "0.4.38" , features = ["serde", "rkyv-64", "alloc"]}
clap = { version = "4.5.21", features = ["derive", "env", "error-context", "help", "std", "usage"], default-features = false }
futures = { version = "0.3.31" }
image = { version = "0.25.5", default-features = false, features = ["jpeg", "png", "webp"] }
itertools = { version = "0.13.0" }
maud = { version = "0.26.0", features = ["axum"] }
object_store = { version = "0.11.1" }
regex = "1.11.1"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.6.2", features = ["trace"] }
tracing = { version = "0.1.40" }
tracing-subscriber = { version = "0.3.18" }
url = { version = "2.5.4" }
serde = { version = "1.0.215", features = ["derive"] }
anyhow = { version = "1.0.93" }
postcard = { version = "1.1.1", features = ["use-std"]}
validator = { version = "0.19.0" , features = ["derive", "unic"]}
lazy_static = { version = "1.5.0" }
bytes = { version = "1.9.0" }
thiserror = "2.0.9"
tower = { version = "0.5.2" , features = ["timeout"]}
pulldown-cmark = { version = "0.12.2", default-features = false, features = ["html"] }
xmlparser = "0.13.6"
